import type { ServicePlan, PlanEnrollment, EntitlementTransaction, PlanPnLRow } from './types';

export const SERVICE_PLANS: ServicePlan[] = [
  {
    id: 'plan-1',
    shopId: 'shop-1',
    name: 'Tire Care Plan',
    description: 'Keep your tires in top shape with scheduled rotations, flat protection, and priority service.',
    billingCadence: 'annual',
    basePrice: 79.99,
    entitlements: [],
    exclusions: ['New tire purchases', 'Specialty vehicle tires (dual rear wheel, oversized)'],
    termMonths: 12,
    autoRenew: true,
    cancellationPolicy: 'end_of_period',
    customerSelfEnrollable: true,
    active: true,
    color: '#C0392B',
    tiers: [
      {
        id: 'tier-1a',
        planId: 'plan-1',
        name: 'Basic',
        price: 79.99,
        entitlements: [
          { type: 'free_service', serviceId: 'st-3', serviceName: 'Tire Rotation', quantityPerPeriod: 2 },
          { type: 'discount', discountPct: 10, label: '10% off additional tire services' },
        ],
      },
      {
        id: 'tier-1b',
        planId: 'plan-1',
        name: 'Standard',
        price: 149.99,
        highlight: true,
        entitlements: [
          { type: 'free_service', serviceId: 'st-3', serviceName: 'Tire Rotation', quantityPerPeriod: 4 },
          { type: 'free_service', serviceId: 'st-4', serviceName: 'Tire Balance', quantityPerPeriod: 2 },
          { type: 'discount', discountPct: 15, label: '15% off additional tire services' },
          { type: 'priority_booking', description: 'Jump the waitlist on all bookings' },
        ],
      },
      {
        id: 'tier-1c',
        planId: 'plan-1',
        name: 'Premium',
        price: 229.99,
        entitlements: [
          { type: 'free_service', serviceId: 'st-3', serviceName: 'Tire Rotation', quantityPerPeriod: 4 },
          { type: 'free_service', serviceId: 'st-4', serviceName: 'Tire Balance', quantityPerPeriod: 4 },
          { type: 'free_service', serviceId: 'st-7', serviceName: 'Flat Tire Repair', quantityPerPeriod: 2 },
          { type: 'discount', discountPct: 20, label: '20% off additional services' },
          { type: 'priority_booking', description: 'Top-priority booking across all service types' },
          { type: 'addon_included', addonId: 'ao-1', addonName: 'Nitrogen Fill (per visit)' },
        ],
      },
    ],
  },
  {
    id: 'plan-2',
    shopId: 'shop-1',
    name: 'Fleet Maintenance Pack',
    description: 'Designed for business fleet managers — unlimited rotations, dedicated scheduling window, and a fleet rep.',
    billingCadence: 'monthly',
    basePrice: 299.99,
    entitlements: [],
    exclusions: ['Consumer personal vehicles', 'Damage repair (collision, vandalism)'],
    termMonths: 3,
    autoRenew: true,
    cancellationPolicy: 'end_of_period',
    customerSelfEnrollable: false,
    active: true,
    color: '#1D4ED8',
    tiers: [
      {
        id: 'tier-2a',
        planId: 'plan-2',
        name: 'Fleet Starter (up to 5 vehicles)',
        price: 299.99,
        entitlements: [
          { type: 'free_service', serviceId: 'st-3', serviceName: 'Tire Rotation', quantityPerPeriod: 10 },
          { type: 'discount', discountPct: 20, label: '20% off all labor' },
          { type: 'priority_booking', description: 'Dedicated morning fleet window (7–9am)' },
        ],
      },
      {
        id: 'tier-2b',
        planId: 'plan-2',
        name: 'Fleet Pro (up to 20 vehicles)',
        price: 899.99,
        highlight: true,
        entitlements: [
          { type: 'free_service', serviceId: 'st-3', serviceName: 'Tire Rotation', quantityPerPeriod: 40 },
          { type: 'free_service', serviceId: 'st-5', serviceName: 'TPMS Reset', quantityPerPeriod: 20 },
          { type: 'discount', discountPct: 25, label: '25% off all labor' },
          { type: 'priority_booking', description: 'Dedicated fleet scheduling team + morning window' },
          { type: 'addon_included', addonId: 'ao-4', addonName: 'Valve Stem Replacement (unlimited)' },
        ],
      },
    ],
  },
  {
    id: 'plan-3',
    shopId: 'shop-1',
    name: 'TPMS Shield',
    description: 'Annual sensor protection — covers resets, replacements, and diagnostic checks all year long.',
    billingCadence: 'annual',
    basePrice: 49.99,
    entitlements: [],
    exclusions: ['Sensor damage from wheel damage events'],
    termMonths: 12,
    autoRenew: true,
    cancellationPolicy: 'end_of_period',
    customerSelfEnrollable: true,
    active: false,
    color: '#059669',
    tiers: [
      {
        id: 'tier-3a',
        planId: 'plan-3',
        name: 'Standard',
        price: 49.99,
        highlight: true,
        entitlements: [
          { type: 'free_service', serviceId: 'st-5', serviceName: 'TPMS Reset', quantityPerPeriod: 4 },
          { type: 'free_service', serviceId: 'st-6', serviceName: 'TPMS Sensor Replacement', quantityPerPeriod: 1 },
          { type: 'discount', discountPct: 15, label: '15% off additional TPMS services' },
        ],
      },
    ],
  },
];

export const PLAN_ENROLLMENTS: PlanEnrollment[] = [
  {
    id: 'enr-1',
    shopId: 'shop-1',
    customerId: 'cust-1',
    customerName: 'Sarah Chen',
    vehicleId: 'veh-1',
    vehicleLabel: '2022 Toyota RAV4',
    planId: 'plan-1',
    planName: 'Tire Care Plan',
    tierId: 'tier-1b',
    tierName: 'Standard',
    tierPrice: 149.99,
    billingCadence: 'annual',
    stripeSubscriptionId: 'sub_ABC123',
    status: 'active',
    termStart: '2026-01-15',
    termEnd: '2027-01-14',
    nextBillingDate: '2027-01-15',
    paymentMethod: 'card',
    paymentLast4: '4242',
    entitlementUsage: [
      { entitlementKey: 'free_rotation', serviceName: 'Tire Rotation', used: 1, included: 4 },
      { entitlementKey: 'free_balance', serviceName: 'Tire Balance', used: 0, included: 2 },
    ],
  },
  {
    id: 'enr-2',
    shopId: 'shop-1',
    customerId: 'cust-2',
    customerName: 'Marcus Johnson',
    vehicleId: 'veh-2',
    vehicleLabel: '2020 Ford F-150',
    planId: 'plan-1',
    planName: 'Tire Care Plan',
    tierId: 'tier-1c',
    tierName: 'Premium',
    tierPrice: 229.99,
    billingCadence: 'annual',
    stripeSubscriptionId: 'sub_DEF456',
    status: 'active',
    termStart: '2026-03-01',
    termEnd: '2027-02-28',
    nextBillingDate: '2027-03-01',
    paymentMethod: 'card',
    paymentLast4: '5555',
    entitlementUsage: [
      { entitlementKey: 'free_rotation', serviceName: 'Tire Rotation', used: 2, included: 4 },
      { entitlementKey: 'free_balance', serviceName: 'Tire Balance', used: 1, included: 4 },
      { entitlementKey: 'free_flat', serviceName: 'Flat Tire Repair', used: 0, included: 2 },
    ],
  },
  {
    id: 'enr-3',
    shopId: 'shop-1',
    customerId: 'cust-3',
    customerName: 'Acme Deliveries LLC',
    vehicleId: 'fleet-1',
    vehicleLabel: 'Fleet (8 vehicles)',
    planId: 'plan-2',
    planName: 'Fleet Maintenance Pack',
    tierId: 'tier-2a',
    tierName: 'Fleet Starter (up to 5 vehicles)',
    tierPrice: 299.99,
    billingCadence: 'monthly',
    stripeSubscriptionId: 'sub_GHI789',
    status: 'active',
    termStart: '2026-04-01',
    termEnd: '2026-07-01',
    nextBillingDate: '2026-07-01',
    paymentMethod: 'ach',
    paymentLast4: '6789',
    entitlementUsage: [
      { entitlementKey: 'free_rotation', serviceName: 'Tire Rotation', used: 7, included: 10 },
    ],
  },
  {
    id: 'enr-4',
    shopId: 'shop-1',
    customerId: 'cust-4',
    customerName: 'Diana Ruiz',
    vehicleId: 'veh-4',
    vehicleLabel: '2019 Honda Civic',
    planId: 'plan-1',
    planName: 'Tire Care Plan',
    tierId: 'tier-1a',
    tierName: 'Basic',
    tierPrice: 79.99,
    billingCadence: 'annual',
    stripeSubscriptionId: 'sub_JKL012',
    status: 'past_due',
    termStart: '2025-12-01',
    termEnd: '2026-11-30',
    nextBillingDate: '2026-06-01',
    paymentMethod: 'card',
    paymentLast4: '1234',
    entitlementUsage: [
      { entitlementKey: 'free_rotation', serviceName: 'Tire Rotation', used: 2, included: 2 },
    ],
  },
  {
    id: 'enr-5',
    shopId: 'shop-1',
    customerId: 'cust-5',
    customerName: 'Ben Nakamura',
    vehicleId: 'veh-5',
    vehicleLabel: '2021 Subaru Outback',
    planId: 'plan-1',
    planName: 'Tire Care Plan',
    tierId: 'tier-1b',
    tierName: 'Standard',
    tierPrice: 149.99,
    billingCadence: 'annual',
    stripeSubscriptionId: 'sub_MNO345',
    status: 'cancelled',
    termStart: '2025-06-01',
    termEnd: '2026-05-31',
    nextBillingDate: '—',
    paymentMethod: 'card',
    paymentLast4: '9999',
    entitlementUsage: [
      { entitlementKey: 'free_rotation', serviceName: 'Tire Rotation', used: 3, included: 4 },
      { entitlementKey: 'free_balance', serviceName: 'Tire Balance', used: 2, included: 2 },
    ],
  },
];

export const ENTITLEMENT_TRANSACTIONS: EntitlementTransaction[] = [
  {
    id: 'etx-1',
    enrollmentId: 'enr-1',
    visitId: 'v-101',
    type: 'free_service',
    description: 'Tire Rotation — covered by Tire Care Plan Standard',
    amountSaved: 19.99,
    createdAt: '2026-03-12T09:30:00Z',
  },
  {
    id: 'etx-2',
    enrollmentId: 'enr-2',
    visitId: 'v-102',
    type: 'free_service',
    description: 'Tire Rotation (1 of 4) — covered by Tire Care Plan Premium',
    amountSaved: 19.99,
    createdAt: '2026-04-05T14:00:00Z',
  },
  {
    id: 'etx-3',
    enrollmentId: 'enr-2',
    visitId: 'v-103',
    type: 'discount',
    description: '20% discount on 4-Tire Mount & Balance (Premium tier)',
    amountSaved: 18.00,
    createdAt: '2026-05-20T11:15:00Z',
  },
  {
    id: 'etx-4',
    enrollmentId: 'enr-3',
    visitId: 'v-104',
    type: 'free_service',
    description: 'Tire Rotation (7 of 10) — Fleet Maintenance Pack Starter',
    amountSaved: 19.99,
    createdAt: '2026-06-01T08:00:00Z',
  },
];

export const PLAN_PNL: PlanPnLRow[] = [
  {
    planId: 'plan-1',
    planName: 'Tire Care Plan',
    tierName: 'Basic',
    enrolledCount: 1,
    mrr: 6.67,
    totalServicesDelivered: 2,
    costOfServicesUnderEntitlement: 39.98,
    netContribution: 79.99 - 39.98,
  },
  {
    planId: 'plan-1',
    planName: 'Tire Care Plan',
    tierName: 'Standard',
    enrolledCount: 2,
    mrr: 25.00,
    totalServicesDelivered: 4,
    costOfServicesUnderEntitlement: 59.98,
    netContribution: 299.98 - 59.98,
  },
  {
    planId: 'plan-1',
    planName: 'Tire Care Plan',
    tierName: 'Premium',
    enrolledCount: 1,
    mrr: 19.17,
    totalServicesDelivered: 3,
    costOfServicesUnderEntitlement: 57.98,
    netContribution: 229.99 - 57.98,
  },
  {
    planId: 'plan-2',
    planName: 'Fleet Maintenance Pack',
    tierName: 'Fleet Starter',
    enrolledCount: 1,
    mrr: 299.99,
    totalServicesDelivered: 7,
    costOfServicesUnderEntitlement: 139.93,
    netContribution: 299.99 - 139.93,
  },
];
